<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipiosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('municipios')->insert([
            ['id'=>1, 'nome'=>'Ambriz', 'provincia_id'=>1],
            ['id'=>2, 'nome'=>'Bula Atumba', 'provincia_id'=>1],
            ['id'=>3, 'nome'=>'Dembos', 'provincia_id'=>1],
            ['id'=>4, 'nome'=>'Nambuangongo', 'provincia_id'=>1],
            ['id'=>5, 'nome'=>'Pango Aluquém', 'provincia_id'=>1],
            ['id'=>6, 'nome'=>'Balombo', 'provincia_id'=>2],
            ['id'=>7, 'nome'=>'Baía Farta', 'provincia_id'=>2],
            ['id'=>8, 'nome'=>'Benguela', 'provincia_id'=>2],
            ['id'=>9, 'nome'=>'Bocoio', 'provincia_id'=>2],
            ['id'=>10, 'nome'=>'Caimbambo', 'provincia_id'=>2],
            ['id'=>11, 'nome'=>'Catumbela', 'provincia_id'=>2],
            ['id'=>12, 'nome'=>'Chongorói', 'provincia_id'=>2],
            ['id'=>13, 'nome'=>'Cubal', 'provincia_id'=>2],
            ['id'=>14, 'nome'=>'Ganda', 'provincia_id'=>2],
            ['id'=>15, 'nome'=>'Lobito', 'provincia_id'=>2],
            ['id'=>16, 'nome'=>'Andulo', 'provincia_id'=>3],
            ['id'=>17, 'nome'=>'Camacupa', 'provincia_id'=>3],
            ['id'=>18, 'nome'=>'Catabola', 'provincia_id'=>3],
            ['id'=>19, 'nome'=>'Chinguar', 'provincia_id'=>3],
            ['id'=>20, 'nome'=>'Chitembo', 'provincia_id'=>3],
            ['id'=>21, 'nome'=>'Cuemba', 'provincia_id'=>3],
            ['id'=>22, 'nome'=>'Cunhinga', 'provincia_id'=>3],
            ['id'=>23, 'nome'=>'Kuito', 'provincia_id'=>3],
            ['id'=>24, 'nome'=>'Nharea', 'provincia_id'=>3],
            ['id'=>25, 'nome'=>'Belize', 'provincia_id'=>4],
            ['id'=>26, 'nome'=>'Buco-Zau', 'provincia_id'=>4],
            ['id'=>27, 'nome'=>'Cabinda', 'provincia_id'=>4],
            ['id'=>28, 'nome'=>'Cacongo', 'provincia_id'=>4],
            ['id'=>29, 'nome'=>'Calai', 'provincia_id'=>5],
            ['id'=>30, 'nome'=>'Cuangar', 'provincia_id'=>5],
            ['id'=>31, 'nome'=>'Cuchi', 'provincia_id'=>5],
            ['id'=>32, 'nome'=>'Cuito Cuanavale', 'provincia_id'=>5],
            ['id'=>33, 'nome'=>'Dirico', 'provincia_id'=>5],
            ['id'=>34, 'nome'=>'Longa', 'provincia_id'=>5],
            ['id'=>35, 'nome'=>'Mavinga', 'provincia_id'=>5],
            ['id'=>36, 'nome'=>'Menongue', 'provincia_id'=>5],
            ['id'=>37, 'nome'=>'Nancova', 'provincia_id'=>5],
            ['id'=>38, 'nome'=>'Rivungo', 'provincia_id'=>5],
            ['id'=>39, 'nome'=>'Amboim', 'provincia_id'=>6],
            ['id'=>40, 'nome'=>'Cassongue', 'provincia_id'=>6],
            ['id'=>41, 'nome'=>'Cela', 'provincia_id'=>6],
            ['id'=>42, 'nome'=>'Conda', 'provincia_id'=>6],
            ['id'=>43, 'nome'=>'Ebo', 'provincia_id'=>6],
            ['id'=>44, 'nome'=>'Libolo', 'provincia_id'=>6],
            ['id'=>45, 'nome'=>'Mussende', 'provincia_id'=>6],
            ['id'=>46, 'nome'=>'Porto Amboim', 'provincia_id'=>6],
            ['id'=>47, 'nome'=>'Quibala', 'provincia_id'=>6],
            ['id'=>48, 'nome'=>'Quilenda', 'provincia_id'=>6],
            ['id'=>49, 'nome'=>'Seles', 'provincia_id'=>6],
            ['id'=>50, 'nome'=>'Sumbe', 'provincia_id'=>6],
            ['id'=>51, 'nome'=>'Ambaca', 'provincia_id'=>7],
            ['id'=>52, 'nome'=>'Banga', 'provincia_id'=>7],
            ['id'=>53, 'nome'=>'Bolongongo', 'provincia_id'=>7],
            ['id'=>54, 'nome'=>'Cambambe', 'provincia_id'=>7],
            ['id'=>55, 'nome'=>'Cazengo', 'provincia_id'=>7],
            ['id'=>56, 'nome'=>'Golungo Alto', 'provincia_id'=>7],
            ['id'=>57, 'nome'=>'Gonguembo', 'provincia_id'=>7],
            ['id'=>58, 'nome'=>'Lucala', 'provincia_id'=>7],
            ['id'=>59, 'nome'=>'Quiculungo', 'provincia_id'=>7],
            ['id'=>60, 'nome'=>'Samba Caju', 'provincia_id'=>7],
            ['id'=>61, 'nome'=>'Cahama', 'provincia_id'=>8],
            ['id'=>62, 'nome'=>'Cuanhama', 'provincia_id'=>8],
            ['id'=>63, 'nome'=>'Curoca', 'provincia_id'=>8],
            ['id'=>64, 'nome'=>'Cuvelai', 'provincia_id'=>8],
            ['id'=>65, 'nome'=>'Namacunde', 'provincia_id'=>8],
            ['id'=>66, 'nome'=>'Ombadja', 'provincia_id'=>8],
            ['id'=>67, 'nome'=>'Bailundo', 'provincia_id'=>9],
            ['id'=>68, 'nome'=>'Catchiungo', 'provincia_id'=>9],
            ['id'=>69, 'nome'=>'Caála', 'provincia_id'=>9],
            ['id'=>70, 'nome'=>'Ekunha', 'provincia_id'=>9],
            ['id'=>71, 'nome'=>'Huambo', 'provincia_id'=>9],
            ['id'=>72, 'nome'=>'Londuimbale', 'provincia_id'=>9],
            ['id'=>73, 'nome'=>'Longonjo', 'provincia_id'=>9],
            ['id'=>74, 'nome'=>'Mungo', 'provincia_id'=>9],
            ['id'=>75, 'nome'=>'Tchicala-Tcholoanga', 'provincia_id'=>9],
            ['id'=>76, 'nome'=>'Tchindjenje', 'provincia_id'=>9],
            ['id'=>77, 'nome'=>'Ucuma', 'provincia_id'=>9],
            ['id'=>78, 'nome'=>'Caconda', 'provincia_id'=>10],
            ['id'=>79, 'nome'=>'Cacula', 'provincia_id'=>10],
            ['id'=>80, 'nome'=>'Caluquembe', 'provincia_id'=>10],
            ['id'=>81, 'nome'=>'Chiange', 'provincia_id'=>10],
            ['id'=>82, 'nome'=>'Chibia', 'provincia_id'=>10],
            ['id'=>83, 'nome'=>'Chicomba', 'provincia_id'=>10],
            ['id'=>84, 'nome'=>'Chipindo', 'provincia_id'=>10],
            ['id'=>85, 'nome'=>'Cuvango', 'provincia_id'=>10],
            ['id'=>86, 'nome'=>'Humpata', 'provincia_id'=>10],
            ['id'=>87, 'nome'=>'Jamba', 'provincia_id'=>10],
            ['id'=>88, 'nome'=>'Lubango', 'provincia_id'=>10],
            ['id'=>89, 'nome'=>'Matala', 'provincia_id'=>10],
            ['id'=>90, 'nome'=>'Quilengues', 'provincia_id'=>10],
            ['id'=>91, 'nome'=>'Quipungo', 'provincia_id'=>10],
            ['id'=>92, 'nome'=>'Belas', 'provincia_id'=>11],
            ['id'=>93, 'nome'=>'Cacuaco', 'provincia_id'=>11],
            ['id'=>94, 'nome'=>'Cazenga', 'provincia_id'=>11],
            ['id'=>95, 'nome'=>'Ícolo e Bengo', 'provincia_id'=>11],
            ['id'=>96, 'nome'=>'Luanda', 'provincia_id'=>11],
            ['id'=>97, 'nome'=>'Quiçama', 'provincia_id'=>11],
            ['id'=>98, 'nome'=>'Viana', 'provincia_id'=>11],
            ['id'=>99, 'nome'=>'Cambulo', 'provincia_id'=>12],
            ['id'=>100, 'nome'=>'Capenda-Camulemba', 'provincia_id'=>12],
            ['id'=>101, 'nome'=>'Caungula', 'provincia_id'=>12],
            ['id'=>102, 'nome'=>'Chitato', 'provincia_id'=>12],
            ['id'=>103, 'nome'=>'Cuango', 'provincia_id'=>12],
            ['id'=>104, 'nome'=>'Cuílo', 'provincia_id'=>12],
            ['id'=>105, 'nome'=>'Lubalo', 'provincia_id'=>12],
            ['id'=>106, 'nome'=>'Lucapa', 'provincia_id'=>12],
            ['id'=>107, 'nome'=>'Xá-Muteba', 'provincia_id'=>12],
            ['id'=>108, 'nome'=>'Cacolo', 'provincia_id'=>13],
            ['id'=>109, 'nome'=>'Dala', 'provincia_id'=>13],
            ['id'=>110, 'nome'=>'Muconda', 'provincia_id'=>13],
            ['id'=>111, 'nome'=>'Saurimo', 'provincia_id'=>13],
            ['id'=>112, 'nome'=>'Cacuso', 'provincia_id'=>14],
            ['id'=>113, 'nome'=>'Calandula', 'provincia_id'=>14],
            ['id'=>114, 'nome'=>'Cambundi-Catembo', 'provincia_id'=>14],
            ['id'=>115, 'nome'=>'Cangandala', 'provincia_id'=>14],
            ['id'=>116, 'nome'=>'Caombo', 'provincia_id'=>14],
            ['id'=>117, 'nome'=>'Cuaba Nzogo', 'provincia_id'=>14],
            ['id'=>118, 'nome'=>'Cunda-Dia-Baze', 'provincia_id'=>14],
            ['id'=>119, 'nome'=>'Luquembo', 'provincia_id'=>14],
            ['id'=>120, 'nome'=>'Malanje', 'provincia_id'=>14],
            ['id'=>121, 'nome'=>'Marimba', 'provincia_id'=>14],
            ['id'=>122, 'nome'=>'Massango', 'provincia_id'=>14],
            ['id'=>123, 'nome'=>'Mucari', 'provincia_id'=>14],
            ['id'=>124, 'nome'=>'Quela', 'provincia_id'=>14],
            ['id'=>125, 'nome'=>'Quirima', 'provincia_id'=>14],
            ['id'=>126, 'nome'=>'Alto Zambeze', 'provincia_id'=>15],
            ['id'=>127, 'nome'=>'Bundas', 'provincia_id'=>15],
            ['id'=>128, 'nome'=>'Camanongue', 'provincia_id'=>15],
            ['id'=>129, 'nome'=>'Léua', 'provincia_id'=>15],
            ['id'=>130, 'nome'=>'Luau', 'provincia_id'=>15],
            ['id'=>131, 'nome'=>'Luacano', 'provincia_id'=>15],
            ['id'=>132, 'nome'=>'Luchazes', 'provincia_id'=>15],
            ['id'=>133, 'nome'=>'Luena', 'provincia_id'=>15],
            ['id'=>134, 'nome'=>'Lumeje', 'provincia_id'=>15],
            ['id'=>135, 'nome'=>'Moxico', 'provincia_id'=>15],
            ['id'=>136, 'nome'=>'Bibala', 'provincia_id'=>16],
            ['id'=>137, 'nome'=>'Camucuio', 'provincia_id'=>16],
            ['id'=>138, 'nome'=>'Namibe', 'provincia_id'=>16],
            ['id'=>139, 'nome'=>'Tômbua', 'provincia_id'=>16],
            ['id'=>140, 'nome'=>'Virei', 'provincia_id'=>16],
            ['id'=>141, 'nome'=>'Alto Cauale', 'provincia_id'=>17],
            ['id'=>142, 'nome'=>'Ambuíla', 'provincia_id'=>17],
            ['id'=>143, 'nome'=>'Bembe', 'provincia_id'=>17],
            ['id'=>144, 'nome'=>'Buengas', 'provincia_id'=>17],
            ['id'=>145, 'nome'=>'Bungo', 'provincia_id'=>17],
            ['id'=>146, 'nome'=>'Damba', 'provincia_id'=>17],
            ['id'=>147, 'nome'=>'Macocola', 'provincia_id'=>17],
            ['id'=>148, 'nome'=>'Milunga', 'provincia_id'=>17],
            ['id'=>149, 'nome'=>'Mucaba', 'provincia_id'=>17],
            ['id'=>150, 'nome'=>'Negage', 'provincia_id'=>17],
            ['id'=>151, 'nome'=>'Puri', 'provincia_id'=>17],
            ['id'=>152, 'nome'=>'Quimbele', 'provincia_id'=>17],
            ['id'=>153, 'nome'=>'Quitexe', 'provincia_id'=>17],
            ['id'=>154, 'nome'=>'Sanza Pombo', 'provincia_id'=>17],
            ['id'=>155, 'nome'=>'Songo', 'provincia_id'=>17],
            ['id'=>156, 'nome'=>'Uíge', 'provincia_id'=>17],
            ['id'=>157, 'nome'=>'Zombo', 'provincia_id'=>17],
            ['id'=>158, 'nome'=>'Cuimba', 'provincia_id'=>18],
            ['id'=>159, 'nome'=>'M\'Banza Kongo', 'provincia_id'=>18],
            ['id'=>160, 'nome'=>'Noqui', 'provincia_id'=>18],
            ['id'=>161, 'nome'=>'N\'Zeto', 'provincia_id'=>18],
            ['id'=>162, 'nome'=>'Soyo', 'provincia_id'=>18],
            ['id'=>163, 'nome'=>'Tomboco', 'provincia_id'=>18]
        ]);
    }
}
